# Generated by Django 3.2.3 on 2021-07-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_mealtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtime',
            name='date',
            field=models.DateField(verbose_name='meal date'),
        ),
    ]
